FROM node:16.14.2-alpine AS development

WORKDIR /app

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

ARG REACT_APP_SENTRY_DSN
ENV REACT_APP_SENTRY_DSN=$REACT_APP_SENTRY_DSN

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn run build

FROM nginx:alpine as production

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=development /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]